### ISSUE TITLE
checkboxes and radios are not vertically aligned properly

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-3#1122]
Checkboxes and radios are not properly aligned vertically to their labels.

I noticed the issue in Cockpit, but this is also a problem in PatternFly and Bootstrap too. I've seen it in screenshots from several others and have also witnessed it on my own machine.

It affects Firefox (on Linux here, at least) more than Chrome, but affects Chrome and WebKit (Epiphany on Linux) also.

The issue is due to Bootstrap absolutely positioning the checkbox and radio widgets with pixel offsets, assuming the widget itself is a particular pixel size. While this might work on some browsers on some platforms, it does not work properly across all browsers or platforms.

I've checked https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/forms.html in Firefox, Chrome, and Epiphany on Linux.

---

Screenshots on Firefox on Fedora 28 of the above rawgit URL to PatternFly's tests:

![screenshot_2018-08-07 forms - patternfly 1](https://user-images.githubusercontent.com/10246/43764599-1b563e7a-9a2e-11e8-93a1-ca7377178feb.png)

![screenshot_2018-08-07 forms - patternfly 2](https://user-images.githubusercontent.com/10246/43764597-1b39b584-9a2e-11e8-94ef-4bd8b774add3.png)

![screenshot_2018-08-07 forms - patternfly 3](https://user-images.githubusercontent.com/10246/43764596-1b19ed44-9a2e-11e8-9d22-19180bb6afea.png)

![screenshot_2018-08-07 forms - patternfly 4](https://user-images.githubusercontent.com/10246/43764595-1af925be-9a2e-11e8-8ace-e78d27dc3a9b.png)

Screenshot of Bootstrap 3.x:

![screenshot_2018-08-07 css bootstrap](https://user-images.githubusercontent.com/10246/43764638-3f81c350-9a2e-11e8-9793-e0c7adefc3bf.png)

**Comment by garrett** [comment]
## Fix!

### Codepen

I've made a fix. Here's a CodePen: https://codepen.io/garrett/pen/QBVzWW/?editors=0100#0

### Screenshot

Here's a screenshot with Chrome, Firefox, WebKit (Epiphany / GNOME Web), and even IE11.

![checkboxes-and-radio-buttons-vertical-alignment](https://user-images.githubusercontent.com/10246/43770742-7d514f84-9a3d-11e8-9c0d-69377140d427.png)

### Relevant CSS

```css
.checkbox input[type="checkbox"],
.checkbox-inline input[type="checkbox"],
.radio input[type="radio"],
.radio-inline input[type="radio"],
input[type="checkbox"],
input[type="radio"] {
  /* Reset to static positioning (ideally, remove the position: absolute; from Bootstrap) */
  position: static;
  /* Properly align using flex */
  align-self: center;
  /* Align in the case where flex doesn't apply (checkbox & radio addons, mostly) */
  vertical-align: middle;
  /* Setting width and height is optional; alignment works without. However, setting it allows for more predictable layouts. */
  min-width: 16px;
  min-height: 16px;
}

.checkbox input[type="checkbox"],
.checkbox-inline input[type="checkbox"],
.radio input[type="radio"],
.radio-inline input[type="radio"] {
  /* 16 (min-width of input) + 4 = 20 */
  margin: 0 4px 0 -20px;
}

.checkbox label,
.radio label,
.checkbox-inline,
.radio-inline {
  display: inline-flex;
}
```

**Comment by garrett** [comment]
I started to integrate and test this snippet within Cockpit. I think it might need a little tweak (like adding label.checkbox, label.radio to the last block).

I'll finish looking into it in tomorrow, as it's evening here.

**Comment by garrett** [comment]
I've been working on integrating the fix into Cockpit and ran across a few issues. One of the biggest ones is related to using flex, as it removes the space between multiple elements (which is normally a good thing, when flex is concerned)... meaning `<label>`s with sub-tags such as `<strong>`, `<em>`, `<b>`, `<i>`, or `<span>` then have words squeezed next to each other. This is not optimal. So I went back to the pen and revised it until everything worked across browsers again.

Here's the new one, which is much simpler:
https://codepen.io/garrett/pen/YjJMPe?editors=0100#0

```css
/* Use same specificity to undo BootStrap's `position: absolute` */
.checkbox input[type="checkbox"], .checkbox-inline input[type="checkbox"], .radio input[type="radio"], .radio-inline input[type="radio"] {
  position: static;
}

input[type="checkbox"],
input[type="radio"] {
  /* Set size to properly align across browsers. Use min-height, min-width so WebKit doesn't scale widget non-proportionally. */
  min-width: 16px;
  min-height: 16px;
  vertical-align: text-bottom;
  /* (line-height - checkbox-height) / 2 = (20px - 16px) / 2 = 2px */
  margin-top: 2px;
}
```

One of the numbers is a "magic" value based on Bootstrap's & PatternFly's defaults. It's calculated with line-height.

Bootstrap (and therefore PatternFly) currently uses a magic number in much the same way, but doesn't do it properly (as widgets are not consistently sized nor consistently placed), causing alignment issues.

The CSS could be slightly modified to ensure the inputs are within labels or specific classes, for the main block of rules. (The first block is just to re-set position back to static. Ideally, we'd remove that from Bootstrap's rules.)
