### ISSUE TITLE
Slider widget

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#210]
We needed a slider widget for setting sizes for storage in a better way than just typing numbers in.
The code lives in Cockpit right now, but I wanted to see if this is interesting for Patternfly as well.

Here is the pull request for Cockpit https://github.com/cockpit-project/cockpit/pull/3876/
And this is how it looks in action:
![screenshot](https://cloud.githubusercontent.com/assets/209895/13535654/a410e560-e23b-11e5-9fa3-fad54d959aff.png)

**Comment by LHinson** [comment]
Hey @andreasn I've added a Epic for this work in our PF backlog https://patternfly.atlassian.net/browse/PTNFLY-1281

**Comment by andreasn** [comment]
Thanks!

**Comment by andreasn** [comment]
There is also the range widget in html5.
I had some issues getting that to display correctly in Firefox on Fedora though (Chrome displayed it better)
http://www.html5tutorial.info/html5-range.php

**Comment by jawnsy** [comment]
:+1: I was just looking for something like this today. There are of course many slider widgets available, but I wanted one that was consistent with the PatternFly design language.

The best one I've seen so far is the Material Design one ([Polymer paper-slider](https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html&active=paper-slider)) though I haven't done an exhaustive search. It's keyboard accessible, supports "tick marks", snapping to the nearest value (we want to use increments), and has tooltip displays on values. Something similar in PatternFly would be fantastic :smile:

**Comment by jawnsy** [comment]
I've tried an experiment using the [CSS Tricks tutorial for styling range input](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/). Some styles were ~~stolen~~ adopted from @andreasn's pull request with colors from [PatternFly's color palette](https://www.patternfly.org/styles/color-palette/).

I tested this on Firefox 45.4.0 and Chrome 55.0.2883.35 (beta), both on Linux as it's the only system I have available. WebKit styles should apply to Safari and there are IE styles (though I haven't checked what they look like).

**Advantages** of this approach: better accessibility, a more native experience.

**Disadvantages** of this approach: the "filled" part of the slider cannot be colored easily with CSS alone.  [Polymer's paper-slider](https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html&active=paper-slider) works well, but requires a lot of custom elements (building on paper-input and such), so I didn't try to distill it down to a simpler styling - and it's probably an entirely custom element rather than being built on a range input.

I'm starting this discussion here and will follow up with a PR later on (it'd be my first contribution to PatternFly, so I have a lot to learn first!) Hopefully you can help :smile:

**jsfiddle**: https://jsfiddle.net/ez7suLrm/

**Browser Support**: http://caniuse.com/#feat=input-range

**Screenshot**: Chrome 55.0.2883.35 (beta), Linux

![screenshot from 2016-11-09 16-36-41](https://cloud.githubusercontent.com/assets/52710/20160304/cb4b88b4-a69a-11e6-8672-7c262b7eec85.png)

**Screenshot**: Firefox ESR 45.4.0, Linux

![screenshot from 2016-11-09 16-37-36](https://cloud.githubusercontent.com/assets/52710/20160316/e99a99a4-a69a-11e6-98d6-2cb97ebdb167.png)

**Styles**

``` css
.slider {
  -webkit-appearance: none;
  border: none;
  box-shadow: none;
  background: transparent;
}
.slider::-webkit-slider-runnable-track {
  cursor: pointer;
  box-shadow: inset 0 0 1px rgba(0,0,0,0.5);
  height: 5px;
  background: #ededed;
}
.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  cursor: pointer;
  border: 1px solid #00659c;
  border-radius: 9px;
  width: 18px;
  height: 18px;
  background-color: #0088ce;
  background-image: linear-gradient(to bottom,#39a5dc 0%,#0088ce 100%);
  margin-top: -6.6px;
}
.slider::-moz-range-track {
  cursor: pointer;
  box-shadow: inset 0 0 1px rgba(0,0,0,0.5);
  height: 5px;
  background: #ededed;
}
.slider::-moz-range-thumb {
  cursor: pointer;
  border: 1px solid #00659c;
  border-radius: 9px;
  width: 18px;
  height: 18px;
  background-color: #0088ce;
  background-image: linear-gradient(to bottom,#39a5dc 0%,#0088ce 100%);
  margin-top: -6.6px;
}
.slider::-ms-track {
  cursor: pointer;
  height: 5px;
  background: transparent;
  border-color: transparent;
  color: transparent;
}
.slider::-ms-fill-lower {
  background: #7dc3e8;
  border: 0.1px solid #010101;
}
.slider::-ms-fill-upper {
  background: #ededed;
  border: 0.1px solid #010101;
}
.slider::-ms-thumb {
  -webkit-appearance: none;
  cursor: pointer;
  border: 1px solid #00659c;
  border-radius: 9px;
  width: 18px;
  height: 18px;
  background-color: #0088ce;
  background-image: linear-gradient(to bottom,#39a5dc 0%,#0088ce 100%);
  margin-top: -6.6px;
}
```

**HTML**

``` html
<input class="form-control slider" name="addon_memory" type="range" min="0" max="100" />
<input class="form-control slider" name="addon_storage" type="range" min="0" max="250" />
```
