### ISSUE TITLE
[Feature Request] - Colors for badges

### ISSUE THREAD

**Issue by thiagodp** [patternfly/patternfly-3#542]
Bootstrap 3 doesn't support colors on badges by default. It would be interesting if PatternFly could add these, maybe adapting some colors:
```css
.badge-error {
	background-color: #b94a48;
}

.badge-warning {
	background-color: #f89406;
}

.badge-warning {
	background-color: #c67605;
}
.badge-success {
	background-color: #468847;
}

.badge-info {
	background-color: #3a87ad;
}

.badge-inverse {
	background-color: #333333;
}
```
So a developer could use it like this:
```html
<div class="badge badge-info" >3</div>
```
