### ISSUE TITLE
Listview heading truncating css

### ISSUE THREAD

**Issue by danseethaler** [patternfly/patternfly-3#887]
I'm working on building the RedHat Repositories page for foreman and am having an issue where the `Listview` actions are bleeding off the edge of the container.

![image](https://user-images.githubusercontent.com/11202705/34012012-269c59fc-e0e0-11e7-98c8-07a07b81d0fa.png)

I'm using the patternfly-react library to implement the component but I'm posting here because it appears to be a css issue.

I found the css below which is applied to the item-header at larger screen sizes. It truncates the header at 25% of the container width and shows an ellipses. When I disable this css the header text wraps around and the action buttons stay within the boundaries. I'm assuming the ellipses is the desired behavior?

```css
@media (min-width: 992px) {
  /* line 46, /home/vagrant/.rvm/gems/ruby-2.2.4/gems/patternfly-sass-3.23.2/assets/stylesheets/patternfly/_list-view.scss */
  .list-view-pf .list-group-item-heading {
    flex: 1 0 calc(25% - 20px);
    float: left;
    font-size: 12px;
    margin: 0 20px 0 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    width: calc(25% - 20px);
  }
}
```

On the page I'm working on the `Listview` is actually split over half the page using a `col-sm-6` from bootstrap. This seems to make the issue more apparent.

I'm new to patternfly so if I'm posting in the wrong place or missing something simple let me know.

Thanks!
